name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: jetrr-haider-ali-1
  GAR_LOCATION: us
  SERVICE: image-search-backend
  REGION: us-central1

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      # Authenticate Docker to Google Cloud Artifact Registry
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v2'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: 'us-docker.pkg.dev'

      - name: Build and Push Container
        run: |-
          docker build -t "us-docker.pkg.dev/jetrr-haider-ali-1/gcr.io/image-search-backend:${{ github.sha }}" -f web-server/Dockerfile ./web-server
          docker push "us-docker.pkg.dev/jetrr-haider-ali-1/gcr.io/image-search-backend:${{ github.sha }}"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: "us-docker.pkg.dev/jetrr-haider-ali-1/gcr.io/image-search-backend:${{ github.sha }}"

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
